name: Validate PR
on:
  pull_request_target:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch of github/india repo
        uses: actions/checkout@v3
        with:
          ref: main
          path: ./india-main
      - name: Checkout head branch of PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      
